# @package loss
loss_func:
  _target_: pytorch_metric_learning.losses.TripletMarginLoss
  margin: 0.2
  distance:
    _target_: pytorch_metric_learning.distances.LpDistance
    normalize_embeddings: true
  reducer:
    _target_: pytorch_metric_learning.reducers.ThresholdReducer
    low: 0
  swap: true
  smooth_loss: true

mining_func:
  _target_: pytorch_metric_learning.miners.TripletMarginMiner
  margin: 0.2
  distance:
    _target_: pytorch_metric_learning.distances.LpDistance
    normalize_embeddings: true
  type_of_triplets: ${general.type_of_triplet}