# @package data_sampler

train:
  _target_: torch.utils.data.sampler.RandomSampler
  data_source: ${data_dataset.train}

val:
  _target_: torch.utils.data.sampler.SequentialSampler
  data_source: ${data_dataset.val}

test:
  _target_: torch.utils.data.sampler.SequentialSampler
  data_source: ${data_dataset.val}