# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.AlbumentationAugment
  height: 448
  width: 448
val:
  _target_: albumentations.Resize
  height: 448
  width: 448
test:
  _target_: albumentations.Resize
  height: 448
  width: 448