# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.AlbumentationAugment
  height: 512
  width: 512
val:
  _target_: project.augmentation.DefaultAug
  height: 512
  width: 512
test:
  _target_: project.augmentation.DefaultAug
  height: 512
  width: 512