# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.AlbumentationAugment
  height: 260
  width: 260
val:
  _target_: project.augmentation.DefaultAug
  height: 260
  width: 260
test:
  _target_: project.augmentation.DefaultAug
  height: 260
  width: 260