# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.AlbumentationAugment
  height: 300
  width: 300
val:
  _target_: project.augmentation.DefaultAug
  height: 300
  width: 300
test:
  _target_: project.augmentation.DefaultAug
  height: 300
  width: 300