# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.TorchAug
  height: 288
  width: 288
  gray_image: false
  gray_prob: 1
  eraser_aug: false
  eraser_prob: 0.3
val:
  _target_: project.augmentation.DefaultAug
  height: 384
  width: 384
  gray_image: false
  gray_prob: 1
test:
  _target_: project.augmentation.DefaultAug
  height: 384
  width: 384