# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.TorchAug
  height: 260
  width: 260
  gray_image: false
  gray_prob: 1
val:
  _target_: project.augmentation.DefaultAug
  height: 260
  width: 260
  gray_image: false
  gray_prob: 1
test:
  _target_: project.augmentation.DefaultAug
  height: 260
  width: 260