# @package data_image_aug
name: image_augment

train:
  _target_: project.augmentation.TorchAug
  height: 448
  width: 448
val:
  _target_: project.augmentation.DefaultAug
  height: 448
  width: 448
test:
  _target_: project.augmentation.DefaultAug
  height: 260
  width: 260