# @package model
name: resizer_efficientnet_embedding_extractor

_target_: project.model.ResizerEfficientnetEmbeddingExtractor
arch: efficientnet_b3
out_feature: 512
dropout_ratio: 0.2
r: 1
n: 16
image_size: 300