# @package data_loader

train:
  _target_: project.data.ShopeeDatasetLoader
  batch_size: 16
  dataset: ${data_dataset.train}
  sampler: ${data_sampler.train}

val:
  _target_: project.data.ShopeeDatasetLoader
    batch_size: 16
    dataset: ${data_dataset.val}
    sampler: ${data_sampler.val}

test:
  _target_: project.data.ShopeeDatasetLoader
    batch_size: 16
    dataset: ${data_dataset.test}
    sampler: ${data_sampler.test}